ara_to_en = {
    "pero": "Perro",
    "polata": "Money",
    "kabadaro": "Jaguar",
    "wadili": "Man",
    "hiaro": "Woman",
    "ibili": "Child",
    "bunaro": "Brown",
    "karime": "Black",
    "hehe": "Grey",
    "halhira": "White",
    "subule": "Yellow",
    "kore": "Red",
    "blu": "Blue",
    "imoro": "Green",
    "plural_human": {
        "na": "The",
        "naha": "These",
        "nara": "Those",
        "naraha": "Those",
        "narabo": "There"
    },
    "de dyna": "My arm",
    "dyna-ha": "Arm",
    "khabo-ho": "Hand",
    "da-khabo": "My hand",
    "bana-ha": "Liver",
    "thy-bana": "It's liver",
    "botoli": "Bottle",
    "Henk botoli-a": "Henk's bottle",
    "siba": "Stone",
    "ly-siba-n": "His stone",
    "ada": "Tree",
    "d-ada-n": "My tree",
    "karobo": "Plate",
    "wa-karobo-n": "Our plate",
    "by-simaka-i": "You called him",    
    "li simaka-o": "He called us",    
    "ly-simaka bo": "He called you",    
    "tho simaka-i": "She called him",    
    "thy-simaka je": "She called them",    
    "ama to toho?": "What is this?",
    "to kodibio": "The bird",
}
